sudo: required
services: docker
language: minimal

before_script:
  - ./minikube/minikube-create.sh

script:
  - ./minikube/launch.sh

after_success:
  - echo "Push qserv_deploy image to Docker Hub"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./build-image.sh
