sudo: required
services: docker
language: minimal

install:
  - sudo apt-get install socat
  - ./minikube/install-nsenter.sh

before_script:
  - ./minikube/minikube-create.sh

script:
  - ./minikube/launch.sh
