apiVersion: v1
kind: Pod
metadata:
  name: dataloader
  labels:
    app: qserv
    node: dataloader
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - qserv
          - key: statefulset.kubernetes.io/pod-name
            operator: In
            values:
            - qserv-0
        topologyKey: "kubernetes.io/hostname"
  subdomain: qserv
  containers:
    - name: dataloader
      command:
        - tail
        - -f
        - /dev/null
      image: {{ .Values.image.repository }}/qserv:{{ .Values.image.tag }}
      imagePullPolicy: Always
      ports:
      volumeMounts:
      - mountPath: /home/qserv/.lsst
        name: config-dot-lsst
      - mountPath: /secret
        name: secret-wmgr
      - mountPath: /qserv/data
        name: qserv-data
  volumes:
    - name: config-dot-lsst
      configMap:
        name: config-dot-lsst
    - hostPath:
        path: /qserv/data
      name: qserv-data
    - name: secret-wmgr
      secret:
        secretName: secret-wmgr
  restartPolicy: Never
