apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-qserv-data-qserv-1
spec:
  storageClassName: ""
  capacity:
    storage: 3Ti
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gke-qserv-fjammes-0-6d-pvc-bcec1323-0503-11e9-8185-42010a80003e
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qserv-data-qserv-1
spec:
  # It's necessary to specify "" as the storageClassName
  # so that the default storage class won't be used, see
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  storageClassName: ""
  volumeName: pv-qserv-data-qserv-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Ti
