apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-repl-data-repl-db-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Ti
  gcePersistentDisk:
    fsType: ext4
    pdName: gke-qserv-fjammes-070e-pvc-cbaf2442-24d4-11e9-889e-42010a80011f
  storageClassName: ''
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repl-data-repl-db-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Ti
  storageClassName: ''
  volumeName: pv-repl-data-repl-db-0
