apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qserv-data-czar-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      dataid: czar-0
  storageClassName: qserv-local-storage
  volumeMode: Filesystem
