apiVersion: v1
kind: Service
metadata:
  name: qserv
  labels:
    app: qserv
spec:
  ports:
  - port: 1094
    name: xrootd
  clusterIP: None
  selector:
    app: qserv
    headless: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: czar
  labels:
    app: qserv
    tier: czar
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - name: qserv 
      port: 4040
      nodePort: 30040
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: qserv
    tier: czar
---
apiVersion: v1
kind: Service
metadata:
  name: repl-ctl
  labels:
    app: qserv
    tier: repl-ctl
spec:
  ports:
    # the port that this service should serve on
    - name: repl-ctl 
      port: 80
  selector:
    app: qserv
    tier: repl-ctl
