apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    dataid: czar-0
  name: qserv-data-pv-czar-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  local:
    path: /qserv/desc/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ccqserv125
  persistentVolumeReclaimPolicy: Retain
  storageClassName: qserv-local-storage
  volumeMode: Filesystem
