apiVersion: v1
kind: Service
metadata:
  name: qserv
  labels:
    app: qserv
spec:
  ports:
  - port: 1094
    name: xrootd
  clusterIP: None
  selector:
    app: qserv
    headless: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: czar
  labels:
    app: qserv
    tier: czar
spec:
  type: NodePort
  ports:
    - name: qserv 
      port: 4040
      nodePort: 30040
  selector:
    app: qserv
    tier: czar
---
apiVersion: v1
kind: Service
metadata:
  name: repl-ctl
  labels:
    app: qserv
    tier: repl-ctl
spec:
  ports:
    - name: http 
      port: 80
  selector:
    app: qserv
    tier: repl-ctl
---
apiVersion: v1
kind: Service
metadata:
  name: xrootd-mgr-0
  labels:
    app: qserv
    tier: xrootd-mgr-0
spec:
  ports:
    # Used by qserv workers
    - port: 2131
      name: cmsd
    # Used by repl-ctl
    - port: 1094
      name: xrootd
  selector:
    app: qserv
    tier: xrootd-mgr-0
