apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qserv
  labels:
    tier: worker
    app: qserv
spec:
  serviceName: qserv
  podManagementPolicy: "Parallel"
  # replicas is updated by template engine
  replicas: 1
  selector:
    matchLabels:
      tier: worker
      app: qserv
  template:
    metadata:
      labels:
        tier: worker
        app: qserv
        headless: qserv
    spec:
      containers:
        - name: cmsd
          image: "<INI_IMAGE>"
          imagePullPolicy: Always
          args:
            - -S
            - cmsd
          command:
            - /config-start/start.sh
          securityContext:
            capabilities:
              add:
              - IPC_LOCK
          volumeMounts:
          - name: config-xrootd-etc
            mountPath: /config-etc
          - mountPath: /config-start
            name: config-xrootd-start
          - mountPath: /qserv/data
            name: qserv-data
          - name: xrootd-adminpath
            mountPath: /qserv/run/tmp/xrd
        - name: mariadb
          image: "<INI_IMAGE>"
          imagePullPolicy: Always
          command:
            - sh
            - /config-start/start.sh
          livenessProbe:
            tcpSocket:
              port: mariadb
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: mariadb
            initialDelaySeconds: 15
            periodSeconds: 5
          ports:
          - name: mariadb
            containerPort: 3306
          volumeMounts:
          - name: config-mariadb-etc
            mountPath: /config-etc
          - name: config-mariadb-start
            mountPath: /config-start
          - mountPath: /qserv/data
            name: qserv-data
        - name: xrootd
          image: "<INI_IMAGE>"
          imagePullPolicy: Always
          args:
            - /config-start/start.sh
          command:
            - sh
          livenessProbe:
            tcpSocket:
              port: xrootd
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: xrootd
            initialDelaySeconds: 10
            periodSeconds: 5
          ports:
          - name: xrootd
            containerPort: 1094
          securityContext:
            capabilities:
              add:
              - IPC_LOCK
              - SYS_RESOURCE
          volumeMounts:
          - name: config-xrootd-etc
            mountPath: /config-etc
          - name: config-xrootd-start
            mountPath: /config-start
          - mountPath: /qserv/data
            name: qserv-data
          - name: xrootd-adminpath
            mountPath: /qserv/run/tmp/xrd
        - name: wmgr
          command:
            - sh
            - /config-start/start.sh
          env:
            - name: CZAR_DN
              valueFrom:
                configMapKeyRef:
                  name: config-domainnames
                  key: CZAR_DN
          image: "<INI_IMAGE>"
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: wmgr
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: wmgr
            initialDelaySeconds: 10
            periodSeconds: 5
          ports:
          - name: wmgr
            containerPort: 5012
          volumeMounts:
          - mountPath: /config-start
            name: config-wmgr-start
          - mountPath: /config-etc
            name: config-wmgr-etc
          - mountPath: /qserv/data
            name: qserv-data
          - mountPath: /secret-mariadb
            name: secret-mariadb
          - mountPath: /secret-wmgr
            name: secret-wmgr
        - name: repl
          command:
            - sh
            - /config-start/start.sh
          env:
            - name: CZAR_DN
              valueFrom:
                configMapKeyRef:
                  name: config-domainnames
                  key: CZAR_DN
          image: "qserv/replica:tools-w.2018.16-556-g62efc42-dirty"
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
          volumeMounts:
          - mountPath: /config-start
            name: config-repl-wrk-start
          - mountPath: /config-etc
            name: config-repl-wrk-etc
          - mountPath: /qserv/data
            name: qserv-data
      initContainers:
        - command:
          - sh
          - /config-mariadb/mariadb-configure.sh
          env:
            - name: CZAR
              valueFrom:
                configMapKeyRef:
                  name: config-domainnames
                  key: CZAR
          image: "<INI_IMAGE>"
          imagePullPolicy: Always
          name: init-data-dir
          volumeMounts:
          - mountPath: /config-mariadb
            name: config-mariadb-configure
          - mountPath: /config-etc
            name: config-mariadb-etc
          - mountPath: /config-sql/worker
            name: config-sql-worker
          - mountPath: /qserv/data
            name: qserv-data
          - mountPath: /secret-mariadb
            name: secret-mariadb
      volumes:
        - name: config-dot-lsst
          configMap:
            name: config-dot-lsst
        - name: config-mariadb-configure
          configMap:
            name: config-mariadb-configure
        - name: config-mariadb-start
          configMap:
            name: config-mariadb-start
        - name: config-sql-worker
          configMap:
            name: config-sql-worker
        - name: config-xrootd-etc
          configMap:
            name: config-xrootd-etc
        - name: config-xrootd-start
          configMap:
            name: config-xrootd-start
            defaultMode: 0555
        - name: config-domainnames
          configMap:
            name: config-domainnames
        - name: config-mariadb-etc
          configMap:
            name: config-mariadb-etc
        - name: config-proxy-etc
          configMap:
            name: config-proxy-etc
        - name: config-proxy-start
          configMap:
            name: config-proxy-start
            defaultMode: 0755
        - name: config-repl-wrk-etc
          configMap:
            name: config-repl-wrk-etc
        - name: config-repl-wrk-start
          configMap:
            name: config-repl-wrk-start
        - name: config-wmgr-etc
          configMap:
            name: config-wmgr-etc
        - name: config-wmgr-start
          configMap:
            name: config-wmgr-start
        - name: secret-wmgr
          secret:
            secretName: secret-wmgr
        - name: secret-mariadb
          secret:
            secretName: secret-mariadb
        - name: xrootd-adminpath
          emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: qserv-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
