apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: xrootd-mgr
  labels:
    tier: xrootd-mgr
    app: qserv
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: xrootd-mgr
      app: qserv
  serviceName: xrootd-mgr
  template:
    metadata:
      labels:
        tier: xrootd-mgr
        app: qserv
    spec:
      containers:
        - name: cmsd
          image: "<INI_IMAGE>"
          imagePullPolicy: Always
          args:
            - -S
            - cmsd
          command:
            - /config-start/start.sh
          volumeMounts:
          - name: config-xrootd-etc
            mountPath: /config-etc
          - name: config-xrootd-start
            mountPath: /config-start
          - name: xrootd-adminpath
            mountPath: /qserv/run/tmp/xrd
        - name: xrootd
          image: "<INI_IMAGE>"
          imagePullPolicy: Always
          args:
            - /config-start/start.sh
          command:
            - sh
          ports:
          - name: xrootd
            containerPort: 1094
          volumeMounts:
          - name: config-xrootd-etc
            mountPath: /config-etc
          - name: config-xrootd-start
            mountPath: /config-start
          - name: xrootd-adminpath
            mountPath: /qserv/run/tmp/xrd
      volumes:
        - name: config-xrootd-etc
          configMap:
            name: config-xrootd-etc
        - name: config-xrootd-start
          configMap:
            name: config-xrootd-start
            defaultMode: 0555
        - name: xrootd-adminpath
          emptyDir: {}
