apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: <TIER>
  labels:
    tier: <TIER>
    role: backup
    app: qserv
spec:
  selector:
    matchLabels:
      tier: qserv
      role: backup
      app: qserv
  serviceName: qserv
  podManagementPolicy: "Parallel"
  replicas: <WORKER_COUNT>
  template:
    metadata:
      labels:
        tier: qserv
        role: backup
        app: qserv
    spec:
      containers:
        - name: sdk
          image: "google/cloud-sdk:238.0.0"
          imagePullPolicy: Always
          command:
            - <CMD>
          volumeMounts:
          - name: <TIER>-data
            mountPath: /qserv/data
          - name: secret-backup
            mountPath: /secret-backup
          - name: config-backup
            mountPath: /config-backup
      volumes:
        - name: secret-backup
          secret:
            secretName: secret-backup
        - name: config-backup
          configMap:
            name: config-backup
  volumeClaimTemplates:
  - metadata:
      name: <TIER>-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Ti
