apiVersion: v1
kind: Service
metadata:
  name: qserv-master
  labels:
    app: qserv
    node: master
spec:
  type: NodePort
  ports:
  - port: 4040 
    nodePort: 30040 
    name: mysql-proxy
  selector:
    app: qserv
    node: master
