apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qserv
  labels:
    app: qserv
spec:
  serviceName: qserv
  replicas: {{ .Values.replicaCount  }}
  selector:
    matchLabels:
      app: qserv
  template:
    metadata:
      labels:
        app: qserv
    spec:
      containers:
        - name: mariadb
          image: "{{ .Values.image.repository }}/qserv:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - /config-start/start.sh
          livenessProbe:
            tcpSocket:
              port: mariadb-port
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: mariadb-port
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
          - name: mariadb-port
            containerPort: 3306
          volumeMounts:
          - name: config-mariadb-etc
            mountPath: /config-etc
          - name: config-mariadb-start
            mountPath: /config-start
          - mountPath: /qserv/run/tmp
            name: tmp-volume
          - mountPath: /qserv/data
            name: data-volume
        - name: xrootd
          image: "{{ .Values.image.repository }}/qserv:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ if .Values.debug -}}
          command: ["tail", "-f", "/dev/null"]
          {{- else -}}
          command: ["/bin/su"]
          {{- end }}
          args: ["qserv", "-c", "sh /config-start/start.sh"]
          env:
            - name: QSERV_MASTER
              valueFrom:
                configMapKeyRef:
                  name: config-master
                  key: qserv_master
            - name: QSERV_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: config-master
                  key: qserv_domain
            - name: QSERV_MASTER_DN
              valueFrom:
                configMapKeyRef:
                  name: config-master
                  key: qserv_master_dn
          securityContext:
            capabilities:
              add:
              - IPC_LOCK
          volumeMounts:
          - name: config-xrootd-etc
            mountPath: /config-etc
          - name: config-xrootd-start
            mountPath: /config-start
          - mountPath: /qserv/run/tmp
            name: tmp-volume
          - mountPath: /qserv/data
            name: data-volume
        - name: proxy
          command:
            - sh
            - /config-start/start.sh
          image: "{{ .Values.image.repository  }}/qserv:{{ .Values.image.tag  }}"
          imagePullPolicy: {{ .Values.image.pullPolicy  }}
          env:
            - name: QSERV_MASTER
              valueFrom:
                configMapKeyRef:
                  name: config-master
                  key: qserv_master
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - /config-probe/probe.sh
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - /config-probe/probe.sh
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
          - name: proxy-port
            containerPort: 4040
          volumeMounts:
          - mountPath: /home/qserv/.lsst
            name: config-dot-lsst
          - mountPath: /config-start
            name: config-proxy-start
          - mountPath: /config-etc
            name: config-proxy-etc
          - mountPath: /config-probe
            name: config-proxy-probe
          - mountPath: /secret
            name: secret-wmgr
          - mountPath: /qserv/run/tmp
            name: tmp-volume
          - mountPath: /qserv/data
            name: data-volume
        - name: wmgr
          command:
            - sh
            - /config-start/start.sh
          env:
            - name: QSERV_MASTER_DN
              valueFrom:
                configMapKeyRef:
                  name: config-master
                  key: qserv_master_dn
          image: "{{ .Values.image.repository  }}/qserv:{{ .Values.image.tag  }}"
          imagePullPolicy: {{ .Values.image.pullPolicy  }}
          livenessProbe:
            tcpSocket:
              port: 5012
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 5012
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
          - mountPath: /config-start
            name: config-wmgr-start
          - mountPath: /config-etc
            name: config-wmgr-etc
          - mountPath: /secret
            name: secret-wmgr
          - mountPath: /qserv/run/tmp
            name: tmp-volume
          - mountPath: /qserv/data
            name: data-volume
      initContainers:
        - command:
          - sh
          - /config-mariadb/mariadb-configure.sh
          env:
            - name: QSERV_MASTER
              valueFrom:
                configMapKeyRef:
                  name: config-master
                  key: qserv_master
          image: "{{ .Values.image.repository  }}/qserv:{{ .Values.image.tag  }}"
          imagePullPolicy: {{ .Values.image.pullPolicy  }}
          name: init-data-dir
          volumeMounts:
          - mountPath: /config-mariadb
            name: config-mariadb-configure
          - mountPath: /config-etc
            name: config-mariadb-etc
          - mountPath: /config-sql/master
            name: config-sql-master
          - mountPath: /config-sql/worker
            name: config-sql-worker
          - mountPath: /qserv/data
            name: data-volume
      volumes:
        - name: config-dot-lsst
          configMap:
            name: config-dot-lsst
        - name: config-mariadb-configure
          configMap:
            name: config-mariadb-configure
        - name: config-mariadb-start
          configMap:
            name: config-mariadb-start
        - name: config-sql-master
          configMap:
            name: config-sql-master
        - name: config-sql-worker
          configMap:
            name: config-sql-worker
        - name: config-xrootd-etc
          configMap:
            name: config-xrootd-etc
        - name: config-xrootd-start
          configMap:
            name: config-xrootd-start
        - name: config-master
          configMap:
            name: config-master
        - name: config-mariadb-etc
          configMap:
            name: config-mariadb-etc
        - name: config-proxy-etc
          configMap:
            name: config-proxy-etc
        - name: config-proxy-start
          configMap:
            name: config-proxy-start
            defaultMode: 0755
        - name: config-proxy-probe
          configMap:
            name: config-proxy-probe
        - name: config-wmgr-etc
          configMap:
            name: config-wmgr-etc
        - name: config-wmgr-start
          configMap:
            name: config-wmgr-start
        - name: secret-wmgr
          secret:
            secretName: secret-wmgr
        - name: tmp-volume
          emptyDir: {}
        - name: data-volume
          emptyDir: {}

