apiVersion: v1
kind: ConfigMap
metadata:
  name: config-master
data:
  qserv_domain: {{ .Values.qserv.domain }}
  qserv_master: {{ .Values.qserv.master }}
  qserv_master_dn: {{ .Values.qserv.master }}.{{ .Values.qserv.domain }}
---
{{ include "qserv.cm" (dict "Name" "config-dot-lsst" "Path" (.Files.Glob "configmap/dot-lsst/*")) }}
---
{{ include "qserv.cm" (dict "Name" "config-mariadb-configure" "Path" (.Files.Glob "configmap/init/mariadb-configure.sh")) }}
---
{{ include "qserv.cm" (dict "Name" "config-mariadb-start" "Path" (.Files.Glob "configmap/mariadb/start.sh")) }}
---
{{ include "qserv.cm" (dict "Name" "config-sql-master" "Path" (.Files.Glob "configmap/init/sql/master/*")) }}
---
{{ include "qserv.cm" (dict "Name" "config-sql-worker" "Path" (.Files.Glob "configmap/init/sql/worker/*")) }}
---
{{ include "qserv.cm" (dict "Name" "config-mariadb-etc" "Path" (.Files.Glob "configmap/mariadb/etc/my.cnf")) }}
---
{{ include "qserv.cm" (dict "Name" "config-proxy-etc" "Path" (.Files.Glob "configmap/proxy/etc/*")) }}
---
{{ include "qserv.cm" (dict "Name" "config-proxy-start" "Path" (.Files.Glob "configmap/proxy/start.sh")) }}
---
{{ include "qserv.cm" (dict "Name" "config-proxy-probe" "Path" (.Files.Glob "configmap/proxy/probe.sh")) }}
---
{{ include "qserv.cm" (dict "Name" "config-wmgr-etc" "Path" (.Files.Glob "configmap/wmgr/etc/*")) }}
---
{{ include "qserv.cm" (dict "Name" "config-wmgr-start" "Path" (.Files.Glob "configmap/wmgr/start.sh")) }}
---
{{ include "qserv.cm" (dict "Name" "config-xrootd-start" "Path" (.Files.Glob "configmap/xrootd/start.sh")) }}
---
{{ include "qserv.cm" (dict "Name" "config-xrootd-etc" "Path" (.Files.Glob "configmap/xrootd/etc/*")) }}
