apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-qserv-data-qserv-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Ti
  gcePersistentDisk:
    fsType: ext4
    pdName: gke-qserv-cluster-121d-pvc-e75bad67-cb14-11e8-80dc-42010a8002bf
  storageClassName: ''
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qserv-data-qserv-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Ti
  storageClassName: ''
  volumeName: pv-qserv-data-qserv-0
